name: Publish Docker image

on: push
  
jobs:
  build_artifact:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'corretto'
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: dist-folder
          path: |
            /home/runner/work/test-ng-actions/test-ng-actions/frontend/dist
          retention-days: 15